#!/usr/bin/env python3
"""Export one autopilot as a single runnable file.

TEMPORARY TEST HARNESS -- not part of the flight software, and it does not
change any of it: the bundle is the same modules, byte for byte, with an
importer in front of them.

    ./bundle.py booster                 # -> dist/boosterlandAutoland.py
    ./bundle.py plane -o /tmp/fly.py    # -> /tmp/fly.py
    python3 dist/boosterlandAutoland.py --set BOOSTBACK_TOLERANCE_M=250

**Why a loader and not a concatenation.**  Pasting the modules end to end
means choosing an order, and the order is a second copy of the dependency
graph that nothing checks -- it goes stale the first time a module grows an
import.  Here every module's source is carried verbatim and served by a
``sys.meta_path`` finder, so Python resolves the imports itself, in whatever
order they actually happen, exactly as it does from the tree.  ``from . import
vec`` keeps working because the package modules are real packages with a
``__path__``.

**The sources stay readable.**  They are stored as plain text between marker
lines rather than as a compressed blob, because a single-file autopilot that
cannot be read on the machine it was copied to is half of what was asked for.
The marker is checked against every source before writing; a module that
contained one would make the bundle unsplittable, so that is an error rather
than a corrupt file.

What the bundle still needs from the outside world is ``krpc`` -- it talks to
a game over the network and there is no version of that which fits in a file.
Everything else is here, and the tests are not: they replace ``krpc`` with a
fake and belong to the tree.
"""
import argparse
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "# ===== krpcLab bundle module: "
DELIMITER = chr(39) * 3   # the raw string the sources travel in

TARGETS = {
    "booster": ("boosterland.autoland", ["common", "boosterland"],
                "boosterlandAutoland.py"),
    "plane": ("spaceplane.autopilot", ["common", "spaceplane"],
              "spaceplaneAutopilot.py"),
}


def collect(packages):
    """Every module of every package, as ``name -> (is_package, source)``."""
    modules = {}
    for package in packages:
        directory = os.path.join(ROOT, package)
        if not os.path.isdir(directory):
            raise SystemExit("no such package: %s" % package)
        for entry in sorted(os.listdir(directory)):
            if not entry.endswith(".py"):
                continue
            path = os.path.join(directory, entry)
            with open(path, encoding="utf-8") as handle:
                source = handle.read()
            if entry == "__init__.py":
                modules[package] = (True, source)
            else:
                modules["%s.%s" % (package, entry[:-3])] = (False, source)
        # A package with no ``__init__.py`` still has to exist as one.
        modules.setdefault(package, (True, ""))
    return modules


PREAMBLE = '''#!/usr/bin/env python3
"""%(title)s -- a single-file export, generated by bundle.py.

Do not edit this file: it is %(count)d modules of the krpcLab tree copied
verbatim and served to Python by the loader below.  Edit the tree and export
again.

    python3 %(name)s                     # fly, waiting for START in game
    python3 %(name)s --set LOG_INTERVAL_UT=1
    python3 %(name)s --address 192.168.1.5

Needs ``krpc`` installed (``pip install krpc``) and a running game with the
kRPC server started.  Nothing else.
"""
import importlib.abc
import importlib.machinery
import sys
import types

_MARKER = %(marker)r


def _split(blob):
    """Sources back out of the text below, by their marker lines."""
    modules = {}
    name = None
    kind = None
    lines = []
    for line in blob.split("\\n"):
        if line.startswith(_MARKER):
            if name is not None:
                modules[name] = (kind, "\\n".join(lines))
            head = line[len(_MARKER):].strip()
            name, _, kind = head.partition(" ")
            kind = (kind == "package")
            lines = []
        else:
            lines.append(line)
    if name is not None:
        modules[name] = (kind, "\\n".join(lines))
    return modules


class _Bundled(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    """Serve the embedded sources, and let Python do the rest.

    A finder rather than a pile of ``exec`` calls in dependency order: the
    order is the import graph's business, and a hand-maintained copy of it is
    a second source of truth that nothing checks.
    """

    def __init__(self, modules):
        self.modules = modules

    def find_spec(self, name, path=None, target=None):
        if name not in self.modules:
            return None
        is_package, _ = self.modules[name]
        spec = importlib.machinery.ModuleSpec(name, self,
                                              is_package=is_package)
        if is_package:
            # Real packages, so ``from . import vec`` resolves normally.
            spec.submodule_search_locations = []
        return spec

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        _, source = self.modules[module.__name__]
        exec(compile(source, "<bundled %%s>" %% module.__name__, "exec"),
             module.__dict__)


def _install():
    finder = _Bundled(_split(_SOURCES))
    sys.meta_path.insert(0, finder)
    return finder


'''

EPILOGUE = '''

_install()

if __name__ == "__main__":
    import %(entry)s as _entry
    sys.exit(_entry.main())
'''


def build(target):
    entry, packages, default_name = TARGETS[target]
    modules = collect(packages)
    chunks = []
    for name in sorted(modules):
        is_package, source = modules[name]
        if MARKER in source:
            raise SystemExit("%s contains the bundle marker; rename it "
                             "before exporting" % name)
        chunks.append("%s%s %s" % (MARKER, name,
                                   "package" if is_package else "module"))
        chunks.append(source.rstrip("\n"))
    blob = "\n".join(chunks)
    # **The container must not be able to change the code it carries.**
    # The sources go in as one raw string: readable, and nothing in them
    # needs escaping.  But a module containing the closing delimiter, or
    # ending in a backslash, would break out of it.  The first draft
    # quietly rewrote any such delimiter it found -- a bundler editing the
    # flight software on its way out of the door.  This refuses instead,
    # and the trailing newline keeps a final backslash away from the quotes.
    for name, (_, source) in sorted(modules.items()):
        if DELIMITER in source:
            raise SystemExit("%s contains the raw-string delimiter, which "
                             "the bundle cannot carry verbatim" % name)
    body = PREAMBLE % {"title": entry, "count": len(modules),
                       "name": default_name, "marker": MARKER}
    body += "_SOURCES = r" + DELIMITER + "\\\n" + blob + "\n" + DELIMITER + "\n"
    body += EPILOGUE % {"entry": entry}
    return body, default_name, len(modules)


def verify(path, modules):
    """Split the written file again and check every module came out intact.

    The docstring claims "byte for byte", and a claim nothing checks is the
    kind this project keeps paying for.  This reads the bundle back the way
    the loader will, and compares each source against the tree it came from.
    """
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    start = text.index("_SOURCES = r" + DELIMITER) + len("_SOURCES = r") \
        + len(DELIMITER)
    blob = text[start:text.rindex(DELIMITER)]
    if blob.startswith("\\\n"):
        blob = blob[2:]
    seen, name, lines = {}, None, []
    for line in blob.split("\n"):
        if line.startswith(MARKER):
            if name is not None:
                seen[name] = "\n".join(lines)
            name = line[len(MARKER):].strip().split(" ")[0]
            lines = []
        else:
            lines.append(line)
    if name is not None:
        seen[name] = "\n".join(lines)
    for module, (_, source) in modules.items():
        got = seen.get(module)
        if got is None:
            raise SystemExit("%s is missing from the bundle" % module)
        if got.rstrip("\n") != source.rstrip("\n"):
            raise SystemExit("%s came out of the bundle changed" % module)
    extra = set(seen) - set(modules)
    if extra:
        raise SystemExit("bundle carries modules that are not in the tree: %s"
                         % ", ".join(sorted(extra)))
    return len(seen)


def selftest(path, entry):
    """Import the bundle with a stub ``krpc`` and check it really assembled.

    A bundler that emits a file nobody runs is a bundler that emits a broken
    file.  This does not fly anything -- it imports the entry module out of
    the bundle, builds a ``Config``, and applies an override, which is enough
    to prove every module in the graph loaded and the loader is wired up.
    """
    probe = """import sys, types
sys.modules['krpc'] = types.ModuleType('krpc')
sys.argv = ['bundle-selftest']
source = open({path!r}, encoding='utf-8').read()
exec(compile(source, {path!r}, 'exec'), {{'__name__': 'bundled'}})
mod = __import__({entry!r}, fromlist=['x'])
cfg = mod.Config()
loaded = [m for m in sys.modules if m.split('.')[0] in
          ('boosterland', 'spaceplane')]
assert hasattr(mod, 'main'), 'no main() in the entry module'
print('selftest ok: %d modules loaded, %d config fields'
      % (len(loaded), len(vars(cfg))))
""".format(path=path, entry=entry)
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as tmp:
        tmp.write(probe)
        probe_path = tmp.name
    try:
        done = subprocess.run([sys.executable, probe_path],
                              capture_output=True, text=True, cwd="/")
    finally:
        os.unlink(probe_path)
    if done.returncode != 0:
        sys.stderr.write(done.stdout + done.stderr)
        raise SystemExit("bundle selftest failed")
    return done.stdout.strip()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("target", choices=sorted(TARGETS),
                        help="booster = boosterland, plane = spaceplane")
    parser.add_argument("-o", "--out", default=None,
                        help="output file (default: dist/<name>.py)")
    parser.add_argument("--no-selftest", action="store_true",
                        help="skip importing the result to check it works")
    args = parser.parse_args(argv)

    body, default_name, count = build(args.target)
    modules = collect(TARGETS[args.target][1])
    out = args.out or os.path.join(ROOT, "dist", default_name)
    directory = os.path.dirname(os.path.abspath(out))
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(body)
    os.chmod(out, 0o755)

    verify(os.path.abspath(out), modules)
    entry = TARGETS[args.target][0]
    note = ""
    if not args.no_selftest:
        note = "  " + selftest(os.path.abspath(out), entry)
    print("%s  %d modules  %.0f kB%s"
          % (out, count, os.path.getsize(out) / 1024.0, note))
    return 0


if __name__ == "__main__":
    sys.exit(main())
